name: agentdojo
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - cpython=3.12.12
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=21.1.6
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python_abi=3.12
  - pyzmq=27.1.0
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - pip:
      - agentdojo==0.1.35
      - annotated-types==0.7.0
      - anthropic==0.74.1
      - anyio==4.11.0
      - attrs==25.4.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cohere==5.20.0
      - deepdiff==8.6.1
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - email-validator==2.3.0
      - fastavro==1.12.1
      - filelock==3.20.0
      - fsspec==2025.10.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-cloud-aiplatform==1.71.1
      - google-cloud-bigquery==3.38.0
      - google-cloud-core==2.5.0
      - google-cloud-resource-manager==1.15.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-genai==1.52.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - grpc-google-iam-v1==0.14.3
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langchain==1.0.8
      - langchain-core==1.0.7
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.9
      - langsmith==0.4.45
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.5
      - openai==2.8.1
      - orderly-set==5.5.0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - secagent==0.1.0
      - shapely==2.1.2
      - sniffio==1.3.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - tokenizers==0.22.1
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - types-requests==2.32.4.20250913
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uv==0.9.11
      - vertexai==1.71.1
      - websockets==15.0.1
      - xxhash==3.6.0
      - zstandard==0.25.0
prefix: /Users/justin/anaconda3/envs/agentdojo
